"""
Django settings for health_assistant project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import re
from dotenv import load_dotenv
import dj_database_url
from urllib.parse import quote

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv()
load_dotenv(BASE_DIR.parent / '.env')


# Helper function to encode DATABASE_URL components
def encode_database_url(database_url):
    """
    Safely encode DATABASE_URL components (especially password) for proper URL parsing.
    Handles special characters like @, #, $, %, etc. in passwords.
    
    Args:
        database_url: The database URL string (e.g., postgresql://user:pass@host:port/db)
    
    Returns:
        Properly encoded DATABASE_URL string, or None if URL is invalid
    """
    if not database_url:
        return None
    
    try:
        # Check if URL appears to already be encoded (contains % followed by hex digits)
        # If so, return as-is to avoid double encoding
        if re.search(r'%[0-9A-Fa-f]{2}', database_url):
            return database_url
        
        # Use a regex to parse the URL manually to handle special characters
        # We need to be careful with @ symbol as it's used as a delimiter
        # Strategy: Split on '://' first, then find the last '@' as the user/pass delimiter
        
        if '://' not in database_url:
            return database_url
        
        scheme, rest = database_url.split('://', 1)
        
        # Find the last @ which separates user:pass from host
        # This handles passwords that contain @ symbols
        if '@' in rest:
            # Split from the right to get user_pass and host_part
            auth_part, host_part = rest.rsplit('@', 1)
            
            # Split auth_part into username and password
            if ':' in auth_part:
                username, password = auth_part.split(':', 1)
            else:
                username = auth_part
                password = None
        else:
            username = None
            password = None
            host_part = rest
        
        # Encode username and password if they exist
        # Use safe='' to encode all special characters including @, :, /, etc.
        encoded_username = quote(username, safe='') if username else None
        encoded_password = quote(password, safe='') if password else None
        
        # Reconstruct the URL
        encoded_url = f"{scheme}://"
        
        if encoded_username:
            encoded_url += encoded_username
            if encoded_password:
                encoded_url += ':' + encoded_password
            encoded_url += '@'
        
        encoded_url += host_part
        
        return encoded_url
        
    except Exception as e:
        # If parsing fails, return original URL and let dj_database_url handle the error
        print(f"Warning: Could not parse DATABASE_URL for encoding: {e}")
        return database_url


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use DJANGO_SECRET_KEY (preferred) or SECRET_KEY for compatibility
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or os.getenv('SECRET_KEY', 'django-insecure-dev-key-only-for-local-testing')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Parse ALLOWED_HOSTS from environment (supports both DJANGO_ALLOWED_HOSTS and ALLOWED_HOSTS)
def _get_env_list(name, default):
    value = os.getenv(name)
    if value:
        return [item.strip() for item in value.split(',') if item.strip()]
    return default

ALLOWED_HOSTS = _get_env_list('DJANGO_ALLOWED_HOSTS', None) or _get_env_list('ALLOWED_HOSTS', ['testserver', '.localhost', '127.0.0.1', '[::1]', '.azurewebsites.net'])


# Application definition
# Admin interface (only enable Jazzmin in DEBUG mode to avoid startup delays)
if DEBUG:
    INSTALLED_APPS = [
        'jazzmin',  # Fancy admin UI (before django.contrib.admin)
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'rest_framework',
        'rest_framework.authtoken',
        'corsheaders',
        'clinic',
    ]
else:
    # Production: Skip Jazzmin to avoid startup delays
    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'rest_framework',
        'rest_framework.authtoken',
        'corsheaders',
        'clinic',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'clinic.middleware.AuditMiddleware',  # Custom audit logging
]

ROOT_URLCONF = 'health_assistant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'health_assistant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Default to SQLite for development
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
}

# Override with DATABASE_URL if provided (for production)
# Use dj-database-url for automatic parsing (Railway, Render, Heroku compatible)
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    try:
        # Attempt to encode DATABASE_URL to handle special characters in passwords
        encoded_url = encode_database_url(DATABASE_URL)
        
        DATABASES['default'] = dj_database_url.parse(
            encoded_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    except Exception as e:
        print(f"Warning: Failed to parse DATABASE_URL: {e}")
        print(f"Original URL pattern: {DATABASE_URL[:DATABASE_URL.find('://')+3]}***")
        print("Attempting to use individual database environment variables...")
        
        # Fallback to individual variables if DATABASE_URL fails
        if all([os.getenv('DB_NAME'), os.getenv('DB_USER'), os.getenv('DB_PASSWORD'), os.getenv('DB_HOST')]):
            DATABASES['default'] = {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('DB_NAME'),
                'USER': os.getenv('DB_USER'),
                'PASSWORD': os.getenv('DB_PASSWORD'),
                'HOST': os.getenv('DB_HOST'),
                'PORT': os.getenv('DB_PORT', '5432'),
                'CONN_MAX_AGE': 600,
            }
            print("Successfully configured database using individual environment variables.")
        else:
            print("\n" + "="*70)
            print("ERROR: DATABASE CONFIGURATION FAILED")
            print("="*70)
            print("DATABASE_URL parsing failed. This usually happens when:")
            print("  1. Password contains special characters (@, #, $, %, etc.)")
            print("  2. URL components are not properly formatted")
            print("\nSolutions:")
            print("  1. URL-encode your password manually:")
            print("     Python: from urllib.parse import quote; print(quote('your-password', safe=''))")
            print("     Online: https://www.urlencoder.org/")
            print("  2. Use individual environment variables instead:")
            print("     DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT")
            print("\nExample DATABASE_URL with encoded password:")
            print("  postgresql://user:my%40pass%23word@localhost:5432/dbname")
            print("="*70 + "\n")
            raise e

# Support individual DB variables if DATABASE_URL is not provided
elif all([os.getenv('DB_NAME'), os.getenv('DB_USER'), os.getenv('DB_PASSWORD'), os.getenv('DB_HOST')]):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': 600,
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for static files
# Use CompressedStaticFilesStorage instead of CompressedManifestStaticFilesStorage
# to avoid post-processing errors with third-party CSS files (e.g., bootswatch)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'clinic.CustomUser'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS settings (for frontend development)
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

# Parse CORS_ALLOWED_ORIGINS from environment
CORS_ALLOWED_ORIGINS = _get_env_list(
    'CORS_ALLOWED_ORIGINS',
    [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ],
)

import re
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://virtual-health-assistant.*\.vercel\.app$",  # Match all Vercel deployments
    r"^https://.*\.azurewebsites\.net$",  # Match all Azure App Service deployments
]

# Allow credentials (for cookies/auth tokens)
CORS_ALLOW_CREDENTIALS = True

# Allow common headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ML Model settings
ML_MODEL_PATH = BASE_DIR.parent / 'ML' / 'models' / 'disease_predictor_v2.pkl'
ML_DATASETS_PATH = BASE_DIR.parent / 'ML' / 'Datasets' / 'active'

# LLM API Configuration
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
GROQ_API_KEY = os.getenv('GROQ_API_KEY')
COHERE_API_KEY = os.getenv('COHERE_API_KEY')

# Rasa Configuration
RASA_ENABLED = os.getenv('RASA_ENABLED', 'True') == 'True'
RASA_SERVER_URL = os.getenv('RASA_SERVER_URL', 'http://localhost:5005')
RASA_TIMEOUT = int(os.getenv('RASA_TIMEOUT', '60'))  # 60 seconds for ML+LLM hybrid validation
RASA_CONFIDENCE_THRESHOLD = float(os.getenv('RASA_CONFIDENCE_THRESHOLD', '0.6'))

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'] if not DEBUG else ['console'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'clinic': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# CPSU Departments
CPSU_DEPARTMENTS = [
    'College of Agriculture and Forestry',
    'College of Teacher Education',
    'College of Arts and Sciences',
    'College of Hospitality Management',
    'College of Engineering',
    'College of Computer Studies',
    'College of Criminal Justice Education',
]

# Session settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # 24 hours

# Security settings for production
# Allow environment variable override, but default to secure settings in production
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True') == 'True'
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True') == 'True'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # Development settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ========================================
# JAZZMIN ADMIN PANEL CONFIGURATION
# ========================================
JAZZMIN_SETTINGS = {
    # Title on the login screen and in the header
    "site_title": "CPSU Health Admin",
    "site_header": "CPSU Health Assistant",
    "site_brand": "Health Admin Panel",
    "site_logo": None,  # Path to your logo image
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to CPSU Health Assistant Admin",
    
    # Copyright on the footer
    "copyright": "CPSU Virtual Health Assistant - Thesis Project 2024",
    
    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": "clinic.CustomUser",
    
    # Field name on user model that contains avatar image
    "user_avatar": None,
    
    ############
    # Top Menu #
    ############
    
    # Links to put along the top menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "📊 Backend Monitoring", "url": "/api/admin/monitoring/", "permissions": ["auth.view_user"]},
        {"name": "API Documentation", "url": "/api/", "new_window": True},
        {"name": "Support", "url": "https://github.com/souchan25/virtualHealthAssistant", "new_window": True},
    ],
    
    #############
    # User Menu #
    #############
    
    # Additional links to include in the user menu on the top right
    "usermenu_links": [
        {"model": "clinic.customuser"},
    ],
    
    #############
    # Side Menu #
    #############
    
    # Whether to display the side menu
    "show_sidebar": True,
    
    # Whether to aut expand the menu
    "navigation_expanded": True,
    
    # Hide these apps when generating side menu
    "hide_apps": [],
    
    # Hide these models when generating side menu
    "hide_models": [],
    
    # List of apps (and/or models) to base side menu ordering off of
    "order_with_respect_to": [
        "clinic",
        "clinic.customuser",
        "auth",
    ],
    
    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "clinic": [
            {
                "name": "📊 Backend Monitoring", 
                "url": "/api/admin/monitoring/",
                "icon": "fas fa-chart-area",
                "permissions": ["clinic.view_auditlog"]
            },
            {
                "name": "Staff Dashboard", 
                "url": "/staff/",
                "icon": "fas fa-chart-line",
                "permissions": ["clinic.view_customuser"]
            }
        ]
    },
    
    # Custom icons for side menu apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "clinic.customuser": "fas fa-user-circle",
        "clinic.auditlog": "fas fa-history",
    },
    
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,
    
    #############
    # UI Tweaks #
    #############
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    
    ###############
    # Change View #
    ###############
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "clinic.customuser": "collapsible",
        "auth.group": "vertical_tabs"
    },
}

# Jazzmin UI Tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",  # CPSU Green theme
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-success",  # CPSU Green sidebar
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

