# Generated by Django 4.2.23 on 2025-10-29 13:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('school_id', models.CharField(db_index=True, help_text='School ID (immutable)', max_length=20, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Clinic Staff')], default='student', help_text='User role (immutable)', max_length=10)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('cpsu_address', models.CharField(blank=True, max_length=255, verbose_name='CPSU Address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_consent_given', models.BooleanField(default=False, help_text='User consent for health data storage')),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='DepartmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, max_length=100, unique=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('students_with_symptoms', models.PositiveIntegerField(default=0)),
                ('percentage_with_symptoms', models.FloatField(default=0.0)),
                ('top_diseases', models.JSONField(default=list, help_text='[{"disease": "name", "count": N}, ...]')),
                ('communicable_count', models.PositiveIntegerField(default=0)),
                ('non_communicable_count', models.PositiveIntegerField(default=0)),
                ('acute_count', models.PositiveIntegerField(default=0)),
                ('chronic_count', models.PositiveIntegerField(default=0)),
                ('referral_pending_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Statistics',
                'verbose_name_plural': 'Department Statistics',
                'db_table': 'department_stats',
            },
        ),
        migrations.CreateModel(
            name='SymptomRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.JSONField(help_text='List of symptom names (e.g., ["fever", "cough"])')),
                ('duration_days', models.PositiveIntegerField(help_text='How many days symptoms have persisted', validators=[django.core.validators.MinValueValidator(1)])),
                ('severity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=1)),
                ('predicted_disease', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('top_predictions', models.JSONField(blank=True, help_text='Top 3 predictions with confidence scores', null=True)),
                ('on_medication', models.BooleanField(default=False)),
                ('medication_adherence', models.BooleanField(blank=True, help_text='Is student following medication schedule?', null=True)),
                ('is_communicable', models.BooleanField(default=False)),
                ('is_acute', models.BooleanField(default=True)),
                ('icd10_code', models.CharField(blank=True, max_length=10)),
                ('requires_referral', models.BooleanField(default=False)),
                ('referral_triggered', models.BooleanField(default=False)),
                ('referral_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'symptom_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='symptom_rec_student_076cf5_idx'), models.Index(fields=['predicted_disease'], name='symptom_rec_predict_003241_idx'), models.Index(fields=['requires_referral'], name='symptom_rec_require_e0087b_idx'), models.Index(fields=['created_at'], name='symptom_rec_created_3ae296_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True, help_text='Chat session identifier')),
                ('insight_text', models.TextField()),
                ('references', models.JSONField(default=list, help_text='Medical references/sources for insight')),
                ('reliability_score', models.FloatField(help_text='Confidence in insight accuracy (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_insights',
                'ordering': ['-reliability_score', '-generated_at'],
                'indexes': [models.Index(fields=['student', 'session_id'], name='health_insi_student_8062c6_idx'), models.Index(fields=['session_id'], name='health_insi_session_f112ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('granted', 'Consent Granted'), ('revoked', 'Consent Revoked'), ('updated', 'Consent Updated')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='consent_log_user_id_ff0a45_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='english', help_text='Chat language (English, Filipino, local dialect)', max_length=20)),
                ('topics_discussed', models.JSONField(default=list, help_text='Topics covered in session')),
                ('insights_generated_count', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', '-started_at'], name='chat_sessio_student_f391bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'Viewed Record'), ('create', 'Created Record'), ('update', 'Updated Record'), ('delete', 'Deleted Record'), ('export', 'Exported Data'), ('login', 'User Login'), ('logout', 'User Logout'), ('failed_login', 'Failed Login Attempt')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('changes', models.JSONField(default=dict, help_text='What changed (before/after values)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx'), models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['school_id'], name='users_school__965c22_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
    ]
