# Generated by Django 4.2.23 on 2025-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('College of Agriculture and Forestry', 'College of Agriculture and Forestry'), ('College of Teacher Education', 'College of Teacher Education'), ('College of Arts and Sciences', 'College of Arts and Sciences'), ('College of Hospitality Management', 'College of Hospitality Management'), ('College of Engineering', 'College of Engineering'), ('College of Computer Studies', 'College of Computer Studies'), ('College of Criminal Justice Education', 'College of Criminal Justice Education')], max_length=100),
        ),
    ]
