# Generated by Django 4.2.23 on 2025-11-12 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(help_text='Building/room where emergency occurred', max_length=255)),
                ('symptoms', models.JSONField(default=list, help_text='Emergency symptoms if any')),
                ('description', models.TextField(blank=True, help_text='Additional details from student')),
                ('status', models.CharField(choices=[('active', 'Active - Needs Response'), ('responding', 'Staff Responding'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20)),
                ('priority', models.IntegerField(default=100, help_text='Priority score (100 = critical)')),
                ('response_time', models.DateTimeField(blank=True, help_text='When staff first responded', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Staff notes on resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_responses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Alert',
                'verbose_name_plural': 'Emergency Alerts',
                'db_table': 'emergency_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='emergency_a_status_219482_idx'), models.Index(fields=['student', '-created_at'], name='emergency_a_student_f857e3_idx')],
            },
        ),
    ]
