# Generated by Django 4.2.23 on 2025-11-12 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_emergencyalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Medication name (e.g., Paracetamol, Amoxicillin)', max_length=200)),
                ('dosage', models.CharField(help_text='Dosage amount (e.g., 500mg, 2 tablets)', max_length=100)),
                ('frequency', models.CharField(help_text='How often (e.g., 3x daily, every 8 hours, as needed)', max_length=50)),
                ('schedule_times', models.JSONField(default=list, help_text='Specific times to take medication ["08:00", "14:00", "20:00"]')),
                ('start_date', models.DateField(help_text='When to start taking medication')),
                ('end_date', models.DateField(help_text='When to stop taking medication')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions (e.g., take with food, avoid alcohol)')),
                ('purpose', models.CharField(blank=True, help_text='What condition this treats', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether medication is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescribed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
                ('symptom_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to='clinic.symptomrecord')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'medications',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(help_text='Date medication should be taken')),
                ('scheduled_time', models.TimeField(help_text='Time medication should be taken')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('taken_at', models.DateTimeField(blank=True, help_text='When medication was actually taken', null=True)),
                ('notes', models.TextField(blank=True, help_text='Student notes (e.g., felt nauseous, forgot)')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether reminder notification was sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='clinic.medication')),
            ],
            options={
                'verbose_name': 'Medication Log',
                'verbose_name_plural': 'Medication Logs',
                'db_table': 'medication_logs',
                'ordering': ['-scheduled_date', '-scheduled_time'],
                'indexes': [models.Index(fields=['medication', 'status'], name='medication__medicat_0a0a8f_idx'), models.Index(fields=['scheduled_date', 'scheduled_time'], name='medication__schedul_a927fe_idx')],
                'unique_together': {('medication', 'scheduled_date', 'scheduled_time')},
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['student', 'is_active'], name='medications_student_5fa4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['start_date', 'end_date'], name='medications_start_d_8d0395_idx'),
        ),
    ]
