# Generated by Django 4.2.23 on 2025-11-12 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_medication_medicationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(help_text='When follow-up is due (auto: 3 days after symptom report)')),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('response_date', models.DateTimeField(blank=True, help_text='When student responded to follow-up', null=True)),
                ('outcome', models.CharField(blank=True, choices=[('improved', 'Condition Improved'), ('same', 'No Change'), ('worse', 'Condition Worsened'), ('resolved', 'Fully Recovered')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Student notes on recovery progress')),
                ('still_experiencing_symptoms', models.BooleanField(blank=True, help_text='Are original symptoms still present?', null=True)),
                ('new_symptoms', models.JSONField(blank=True, default=list, help_text='Any new symptoms developed since last report')),
                ('review_notes', models.TextField(blank=True, help_text='Staff review notes')),
                ('requires_appointment', models.BooleanField(default=False, help_text='Does student need clinic visit?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_followups', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),
                ('symptom_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='clinic.symptomrecord')),
            ],
            options={
                'verbose_name': 'Follow-Up',
                'verbose_name_plural': 'Follow-Ups',
                'db_table': 'follow_ups',
                'ordering': ['scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'status', 'scheduled_date'], name='follow_ups_student_b95a6f_idx'), models.Index(fields=['scheduled_date', 'status'], name='follow_ups_schedul_4f65cc_idx'), models.Index(fields=['symptom_record'], name='follow_ups_symptom_f310f3_idx')],
            },
        ),
    ]
