# Generated by Django 4.2.23 on 2025-12-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('clinic_staff', 'Clinic Staff'), ('dev', 'Developer')], default='student', help_text='User role (immutable)', max_length=20),
        ),
    ]
